server:
  port: 8060
spring:
  application:
    name: SAPOrgSync
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saporgsync?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
  data:
    mongodb:
      database: LCJ_SAP360
      uri: mongodb://127.0.0.1:27017/LCJ_SAP360
      username: lundong
      password: lundong6666